* Clew Visualiser
  A visualiser for clews retrieved from [[https://github.com/patricknaish/clew-backend][Clew Backend]]
** Clew
   Clew is a tool where someone can record a route through a location
   using their smartphone. Another user, for example someone who is
   partially sighted can play this clew back and move through the
   space more safely as they are taking a route others have used.

* License

  This program is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see
  <http://www.gnu.org/licenses/>.
